### PR TITLE
Add ability to set MaxConcurrentReconciles for controller

### PR DESCRIPTION
**Pull request by walkamongus**
implementation for #83

### CODE REVIEW

**Comment by walkamongus** [comment]
@vazirim tests have been fixed

**Comment by vazirim** [comment]
@walkamongus Thank you for this contribution, it looks good.
Could you please sign the commit (please see below "Learn more about signing commits")?

**Comment by walkamongus** [comment]
@vazirim commit signed and all green!

**Review by vazirim — APPROVED** [review]
LGTM

**Pull request merged**
